### ISSUE TITLE
How way use to gomqtt server

### ISSUE THREAD

**Issue by jacoblai** [gomqtt/router#1]
May i use this router on gomqtt server host，some time i think so maybe like the http api...… ^^

**Comment by 256dpi** [comment]
I'm thinking about extracting some core functionality from the broker package, to allow MQTT server implementations that do not broker messages but handle them in an HTTP API kind of style. Yet, this is a little more complicated as the MQTT spec specifically expects a "server" to be "broker".

**Comment by jacoblai** [comment]
^^ Maybe like the $SYS topic implementations that on my think

**Comment by 256dpi** [comment]
Closing this as the `Backend` interface in the broker package should be enough open to to do something like that already.
